### ISSUE TITLE
[Bug]: unable to build with pnpm

### ISSUE THREAD

**Issue by efrembaraldo** [open-gsd/gsd-pi#1707]
### Bug type

Regression (worked before, now fails)

### Summary

during build the build failed with:
```
> @opengsd/daemon@1.14.0 build /home/opengsd/repos/open-gsd_gsd-pi/packages/daemon
> node ../../scripts/clean-package-dist.cjs && tsc

src/resources/extensions/gsd/model-router.ts:94:3 - error TS1117: An object literal cannot have multiple properties with the same name.

94   "claude-sonnet-5": "standard",           // GA on GitHub Copilot, Anthropic, Vertex, Bedrock
     ~~~~~~~~~~~~~~~~~

src/resources/extensions/gsd/model-router.ts:136:3 - error TS1117: An object literal cannot have multiple properties with the same name.

136   "claude-sonnet-5": 0.003,                // $3.00/M input; matches Sonnet 4.x pricing
      ~~~~~~~~~~~~~~~~~

src/resources/extensions/gsd/model-router.ts:184:3 - error TS1117: An object literal cannot have multiple properties with the same name.

184   "claude-sonnet-5":              { coding: 90, debugging: 85, research: 80, reasoning: 87, speed: 55, longContext: 80, instruction: 88 },
      ~~~~~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: src/resources/extensions/gsd/model-router.ts:94

 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 2.
```

### Steps to reproduce

git clone https://github.com/open-gsd/gsd-pi.git
cd gsd-pi
git reset --hard HEAD && git pull && SHORT=$(git rev-parse --short=8 HEAD) && BASE=$(node -p "require('./package.json').version") && DEV_VERSION="${BASE}-dev.${SHORT}" && echo $DEV_VERSION && npm version "$DEV_VERSION" --no-git-tag-version --allow-same-version && node -e "const f='pkg/package.json';const j=require('./'+f);j.version='$DEV_VERSION';require('fs').writeFileSync(f,JSON.stringify(j,null,2)+'\n')" && corepack enable && corepack prepare pnpm@10.12.1 --activate && pnpm install --frozen-lockfile && pnpm run build 

### Expected behavior

correct compiling for install

### Actual behavior

```
> @opengsd/daemon@1.14.0 build /home/opengsd/repos/open-gsd_gsd-pi/packages/daemon
> node ../../scripts/clean-package-dist.cjs && tsc

src/resources/extensions/gsd/model-router.ts:94:3 - error TS1117: An object literal cannot have multiple properties with the same name.

94   "claude-sonnet-5": "standard",           // GA on GitHub Copilot, Anthropic, Vertex, Bedrock
     ~~~~~~~~~~~~~~~~~

src/resources/extensions/gsd/model-router.ts:136:3 - error TS1117: An object literal cannot have multiple properties with the same name.

136   "claude-sonnet-5": 0.003,                // $3.00/M input; matches Sonnet 4.x pricing
      ~~~~~~~~~~~~~~~~~

src/resources/extensions/gsd/model-router.ts:184:3 - error TS1117: An object literal cannot have multiple properties with the same name.

184   "claude-sonnet-5":              { coding: 90, debugging: 85, research: 80, reasoning: 87, speed: 55, longContext: 80, instruction: 88 },
      ~~~~~~~~~~~~~~~~~
```

### GSD version

v1.14.0-dev.4eeed5c5

### Node.js version

v24.18.0

### Operating system

Debian 13.6

### Install method

npm global install

### Affected area

Other

### Logs, screenshots, and evidence

```shell

```

**Comment by efrembaraldo** [comment]
It appears to be an oversight introduced with commit 42cb8ec3

**Comment by jeremymcs** [comment]
### Issue evaluation - approved

Issue: [[Bug]: unable to build with pnpm](https://github.com/open-gsd/gsd-pi/issues/1707)

Approved for automatic work: the evaluator could not disprove a concrete, surgical issue report and found no safety flags.

Confidence: high (82%)

**Safety flags**
- none

**Labels applied**
- `ready-for-agent`

**Comment by jeremymcs** [comment]
⏳ **Issue work started** — beginning work on [#1707 [Bug]: unable to build with pnpm](https://github.com/open-gsd/gsd-pi/issues/1707).

- Repo: `open-gsd/gsd-pi`
- Issue: [#1707 [Bug]: unable to build with pnpm](https://github.com/open-gsd/gsd-pi/issues/1707)

**Comment by jeremymcs** [comment]
✅ **Issue work verified** — code changes are ready for PR creation on [#1707 [Bug]: unable to build with pnpm](https://github.com/open-gsd/gsd-pi/issues/1707).

- Repo: `open-gsd/gsd-pi`
- Verification passed in the worktree. Opening the PR now.

**Comment by jeremymcs** [comment]
Worked issue #1707 into PR #1708.

## Summary
- Removed duplicate Sonnet 5 model entries and verified all three TS1117 diagnostics are resolved.

## Verification
- Completed in the repository worktree before push.

## Issue
- [#1707 [Bug]: unable to build with pnpm](https://github.com/open-gsd/gsd-pi/issues/1707)
- Repo: `open-gsd/gsd-pi`

## Pull Request
- [#1708](https://github.com/open-gsd/gsd-pi/pull/1708)
- Branch: `issue/1707-bug-unable-to-build-with-pnpm-1786472871`
